
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ludbvzuiebcrpfsvkred.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1ZGJ2enVpZWJjcnBmc3ZrcmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMzI2MDEsImV4cCI6MjA2MTgwODYwMX0.g5TMTa_OklnSeK8sgqr-hlxVgdMAndsLYglq7GzYC74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
